### Programming for Biomedical Informatics
#### Week 3 - Numpy Quick Tour

Here we run quickly through some key functionality for Numpy. It is a hugely rich library which has excellent documentation. Please go here for the official documentation - https://numpy.org

In [1]:
import numpy as np

In [7]:
##Creating Arrays

# 1D array
a = np.array([1, 2, 3, 4])
print(a)
print("")

# 2D array
b = np.array([[1, 2], [3, 4]])
print(b)
print("")

# 3D array
c = np.array([[[1, 2], [3, 4]], [[5, 6], [7, 8]]])
print(c)
print("")

# Create an array of zeros
zeros = np.zeros((3, 3))
print(zeros)
print("")

# Create an array of ones
ones = np.ones((2, 4))
print(ones)
print("")

# Create an array with a range of values
arange = np.arange(0, 10, 2)  # [0, 2, 4, 6, 8]
print(arange)
print("")

# Create a linearly spaced array
linspace = np.linspace(0, 1, 5)  # [0, 0.25, 0.5, 0.75, 1]
print(linspace)
print("")

[1 2 3 4]

[[1 2]
 [3 4]]

[[[1 2]
  [3 4]]

 [[5 6]
  [7 8]]]

[[0. 0. 0.]
 [0. 0. 0.]
 [0. 0. 0.]]

[[1. 1. 1. 1.]
 [1. 1. 1. 1.]]

[0 2 4 6 8]

[0.   0.25 0.5  0.75 1.  ]



In [8]:
## Array Properties
print(a.shape)    # (4,)
print(b.shape)    # (2, 2)
print(b.size)     # 4
print(b.dtype)    # int32 (or equivalent based on the system)

(4,)
(2, 2)
4
int32


In [9]:
## Indexing and Slicing

# 1D array indexing
print(a[1])  # 2

# 2D array indexing
print(b[1, 1])  # 4

# 1D array slicing
print(a[1:3])  # [2, 3] since a begins with 0 

# 2D array slicing
print(b[:, 1])  # [2, 4] (second column)

2
4
[2 3]
[2 4]


In [10]:
## Reshaping Arrays

print(a)

# Reshape a 1D array to a 2D array
reshaped = a.reshape((2, 2))
print(reshaped)

# Flatten a 2D array to a 1D array
flattened = b.flatten()
print(flattened)

[1 2 3 4]
[[1 2]
 [3 4]]
[1 2 3 4]


In [11]:
## Basic Operations

# Element-wise addition, subtraction, multiplication, division
x = np.array([1, 2, 3])
y = np.array([4, 5, 6])

print(x + y)  # [5, 7, 9]
print(x - y)  # [-3, -3, -3]
print(x * y)  # [4, 10, 18]
print(x / y)  # [0.25, 0.4, 0.5]

# Broadcasting
z = 2
print(x)
print(x * z)  # [2, 4, 6]

[5 7 9]
[-3 -3 -3]
[ 4 10 18]
[0.25 0.4  0.5 ]
[1 2 3]
[2 4 6]


In [12]:
## Mathematical Functions

# Square root
sqrt_x = np.sqrt(x)
print(sqrt_x)

# Exponential
exp_x = np.exp(x)
print(exp_x)

# Sine function
sin_x = np.sin(x)
print(sin_x)

# Dot product
print(x,y)
dot_product = np.dot(x, y)  # 1*4 + 2*5 + 3*6 = 32
print(dot_product)

[1.         1.41421356 1.73205081]
[ 2.71828183  7.3890561  20.08553692]
[0.84147098 0.90929743 0.14112001]
[1 2 3] [4 5 6]
32


In [13]:
## Aggregate Functions

# Sum
print(np.sum(x))  # 6

# Mean
print(np.mean(x))  # 2.0

# Maximum and minimum
print(np.max(x))  # 3
print(np.min(x))  # 1

# Standard deviation
print(np.std(x))  # 0.816...

6
2.0
3
1
0.816496580927726


In [14]:
## Logical Operations

# Boolean array based on condition
cond = x > 1  # [False, True, True]

# Select elements using condition
selected = x[x > 1]  # [2, 3]

# Check if any or all elements satisfy a condition
print(np.any(x > 2))  # True
print(np.all(x > 0))  # True

True
True


In [15]:
## Random Number Generation

# Generate random numbers from a uniform distribution
rand_array = np.random.rand(3, 3)

# Generate random integers
rand_ints = np.random.randint(0, 10, (2, 2))

# Set a random seed for reproducibility
np.random.seed(41)
random_sample = np.random.rand(5)
print(random_sample)

[0.25092362 0.04609582 0.67681624 0.04346949 0.1164237 ]


In [16]:
## Stacking and Concatenation

# Vertical stacking
stacked_v = np.vstack((x, y))  # [[1, 2, 3], [4, 5, 6]]
print(stacked_v)

# Horizontal stacking
stacked_h = np.hstack((x, y))  # [1, 2, 3, 4, 5, 6]
print(stacked_h)

# Concatenate arrays along a specified axis
concat = np.concatenate((x, y), axis=0)  # [1, 2, 3, 4, 5, 6]
print(concat)

[[1 2 3]
 [4 5 6]]
[1 2 3 4 5 6]
[1 2 3 4 5 6]


In [17]:
## Linear Algebra

# Matrix multiplication
A = np.array([[1, 2], [3, 4]])
B = np.array([[5, 6], [7, 8]])

result = np.matmul(A, B)  # [[19, 22], [43, 50]]
print(A)
print("")
print(B)
print("")
print(result)
print("")

# Inverse of a matrix
inv_A = np.linalg.inv(A)
print(inv_A)

# Eigenvalues and eigenvectors
eigenvalues, eigenvectors = np.linalg.eig(A)
print(eigenvalues)

[[1 2]
 [3 4]]

[[5 6]
 [7 8]]

[[19 22]
 [43 50]]

[[-2.   1. ]
 [ 1.5 -0.5]]
[-0.37228132  5.37228132]


In [18]:
## Advanced Indexing

# Fancy indexing
print(x)
indices = [0, 2]
print(x[indices])  # [1, 3]

# Boolean indexing
mask = x > 1
print(x[mask])  # [2, 3]

[1 2 3]
[1 3]
[2 3]


In [19]:
## Save and Load Arrays

# Save an array to a file
np.save('my_array.npy', x)

# Load an array from a file
loaded_array = np.load('my_array.npy')